kanban
    backlog[Backlog]
        feature1[New Feature]
        ::icon(fas fa-lightbulb)
        bug1[Bug Fix]
        :::urgent
    inprogress[In Progress]
        task1(Implementing)
    done[Done]
        task2((Completed))