journey
    title Comprehensive Test
    accTitle: Accessible Title
    accDescr {
        Multiline
        Description
    }
    section Section A
      Task A1: 5: User
      Task A2: 3: User, Admin
    section Section B
      Task B1: 1: System
