#define TOK_RBRACE                           1
#define TOK_SCENE                            2
#define TOK_IDENTIFIER                       3
#define TOK_LBRACE                           4
#define TOK_ARTBOARD                         5
#define TOK_COLON                            6
#define TOK_NUMBER                           7
#define TOK_NODE_TYPE                        8
#define TOK_AT                               9
#define TOK_STRING                          10
#define TOK_COLOR                           11
#define TOK_BOOL                            12
#define TOK_DOLLAR                          13
#define TOK_HASH                            14
#define TOK_DOT                             15
#define TOK_BINDING                         16
#define TOK_COMMA                           17
#define TOK_REPEAT                          18
#define TOK_COMPONENT                       19
#define TOK_ANIM                            20
#define TOK_TRACK                           21
#define TOK_SLASH                           22
#define TOK_KEYFRAME                        23
#define TOK_ARROW                           24
#define TOK_MACHINE                         25
#define TOK_LAYER                           26
#define TOK_STATE                           27
#define TOK_TRANSITION                      28
#define TOK_WHEN                            29
#define TOK_GT                              30
#define TOK_LT                              31
#define TOK_EQ                              32
#define TOK_NEQ                             33
#define TOK_DATA                            34
#define TOK_FOR                             35
#define TOK_IN                              36
