/*
 * flexUI Designer - Code Generator Implementation
 */

#include "flexui_designer/code_generator.h"
#include <fstream>

namespace flexui_designer {

std::string CodeGenerator::generate(const std::vector<DesignWidget>& widgets) const {
    std::ostringstream out;

    out << "/*\n";
    out << " * Generated by flexUI Designer\n";
    out << " */\n\n";
    out << "#include <flexUI.h>\n\n";
    out << "void create_ui(flexUI::Box& root) {\n";

    for (const auto& w : widgets) {
        out << generate_widget_code(w, 1);
    }

    out << "}\n";
    return out.str();
}

std::string CodeGenerator::generate_widget_code(const DesignWidget& w, int indent) const {
    std::ostringstream out;
    std::string ind = indent_str(indent);
    std::string type = widget_type_name(w.type);

    out << ind << "// " << w.id << "\n";
    out << ind << "auto* " << w.id << " = root.create<flexUI::" << type << ">();\n";
    out << ind << w.id << "->set_position(" << (int)w.x << ", " << (int)w.y << ");\n";
    out << ind << w.id << "->set_size(" << (int)w.width << ", " << (int)w.height << ");\n";

    switch (w.type) {
        case WidgetType::Button:
        case WidgetType::Label:
        case WidgetType::Checkbox:
        case WidgetType::Card:
            out << ind << w.id << "->set_text(\"" << w.text << "\");\n";
            break;
        case WidgetType::Input:
            out << ind << w.id << "->set_placeholder(\"" << w.text << "\");\n";
            break;
        case WidgetType::Slider:
        case WidgetType::ProgressBar:
            out << ind << w.id << "->set_range(" << w.min_value << ", " << w.max_value << ");\n";
            out << ind << w.id << "->set_value(" << w.value << ");\n";
            break;
        case WidgetType::Dropdown:
            out << ind << w.id << "->set_placeholder(\"" << w.text << "\");\n";
            for (const auto& opt : w.options) {
                out << ind << w.id << "->add_option(\"" << opt << "\");\n";
            }
            break;
        case WidgetType::Tabs:
            for (const auto& tab : w.options) {
                out << ind << w.id << "->add_tab(\"" << tab << "\");\n";
            }
            break;
        default:
            break;
    }

    // Style properties (only if non-default)
    if (w.bg_color != 0x2A2A2EFF) {
        out << ind << w.id << "->style().background = 0x" << std::hex << w.bg_color << std::dec << ";\n";
    }
    if (w.text_color != 0xFFFFFFFF) {
        out << ind << w.id << "->style().text_color = 0x" << std::hex << w.text_color << std::dec << ";\n";
    }
    if (w.border_color != 0x3A3A40FF) {
        out << ind << w.id << "->style().border_color = 0x" << std::hex << w.border_color << std::dec << ";\n";
    }
    if (w.border_width != 1.0f) {
        out << ind << w.id << "->style().border_width = " << w.border_width << "f;\n";
    }
    if (w.border_radius != 4.0f) {
        out << ind << w.id << "->style().border_radius = " << w.border_radius << "f;\n";
    }
    if (w.font_size != 12.0f) {
        out << ind << w.id << "->style().font_size = " << w.font_size << "f;\n";
    }
    if (w.font_bold) {
        out << ind << w.id << "->style().font_bold = true;\n";
    }
    if (w.padding != 8.0f) {
        out << ind << w.id << "->style().padding = " << w.padding << "f;\n";
    }

    // Event handlers
    if (!w.on_click.empty()) {
        out << ind << w.id << "->on_click(" << w.on_click << ");\n";
    }
    if (!w.on_change.empty()) {
        out << ind << w.id << "->on_change(" << w.on_change << ");\n";
    }
    if (!w.on_focus.empty()) {
        out << ind << w.id << "->on_focus(" << w.on_focus << ");\n";
    }
    if (!w.on_blur.empty()) {
        out << ind << w.id << "->on_blur(" << w.on_blur << ");\n";
    }

    out << "\n";
    return out.str();
}

std::string CodeGenerator::widget_type_name(WidgetType type) const {
    switch (type) {
        case WidgetType::Button: return "Button";
        case WidgetType::Label: return "Label";
        case WidgetType::Input: return "Input";
        case WidgetType::Checkbox: return "Checkbox";
        case WidgetType::Switch: return "Switch";
        case WidgetType::Slider: return "Slider";
        case WidgetType::ProgressBar: return "ProgressBar";
        case WidgetType::Dropdown: return "Dropdown";
        case WidgetType::Tabs: return "Tabs";
        case WidgetType::Card: return "Card";
        case WidgetType::Divider: return "Divider";
        case WidgetType::Container: return "Box";
    }
    return "Widget";
}

std::string CodeGenerator::indent_str(int level) const {
    return std::string(level * 4, ' ');
}

bool CodeGenerator::save(const std::string& path, const std::string& code) const {
    std::ofstream file(path);
    if (!file) return false;
    file << code;
    return true;
}

} // namespace flexui_designer
