/*
 * Flex DSL Token Definitions
 * Shared between Lexer (re2c) and Parser (lemon)
 *
 * Token values are defined by lemon parser (flex_parser_gen.h).
 * This file defines special tokens (EOF, ERROR) and common structures.
 */

#pragma once

#include <string>

// Include lemon-generated token definitions (TOK_SCENE, TOK_RECT, etc.)
// This header is generated by lemon in the build directory
#include "flex_parser_gen.h"

namespace flex {
namespace parser {

// ============================================================================
// Special Token Types (not in grammar, lemon uses 0 for EOF internally)
// ============================================================================

constexpr int TOK_EOF = 0;
constexpr int TOK_ERROR = -1;

// ============================================================================
// Token Structure
// ============================================================================

struct Token {
  int type; // Use int for compatibility with lemon
  std::string value;
  int line;
  int column;

  Token() : type(TOK_ERROR), line(0), column(0) {}
  Token(int t, const std::string &v, int l, int c) : type(t), value(v), line(l), column(c) {}
};

// ============================================================================
// Lexer State
// ============================================================================

struct LexerState {
  const char *start;
  const char *cursor;
  const char *marker;
  int line;
  int column;
  Token current_token;
};

// ============================================================================
// Lexer Interface
// ============================================================================

LexerState *lexer_create(const char *source);
void lexer_destroy(LexerState *state);
Token lex_next_token(LexerState *state);

} // namespace parser
} // namespace flex
