add_subdirectory(common)
add_subdirectory(bar)
add_subdirectory(line)
add_subdirectory(arc)
add_subdirectory(area)
add_subdirectory(point)
add_subdirectory(rect)
add_subdirectory(rule)
add_subdirectory(tick)
add_subdirectory(text)
add_subdirectory(pie)
add_subdirectory(radar)
add_subdirectory(boxplot)
add_subdirectory(errorbar)
add_subdirectory(trail)
add_subdirectory(errorband)
add_subdirectory(geoshape)
add_subdirectory(image)
