#include "cssbox_svg_path.h"
#include "svg_path_lexer_gen.c"  // Generated by re2c

namespace cssbox {

std::vector<PathCommand> SVGPathParser::parse(const std::string& d_attr) {
    std::vector<PathCommand> commands;

    // Null-terminate the input for re2c
    std::string input = d_attr + '\0';

    SVGPathLexer lexer;
    SVGPathLexer_init(&lexer, input.c_str());

    SVGPathToken token;
    PathCommand current_cmd;
    char last_cmd_type = 0;
    bool last_cmd_relative = false;

    while (true) {
        token = SVGPathLexer_next_token(&lexer);

        if (token.type == END) {
            break;
        }

        // Check if it's a command token
        bool is_command = (token.type != NUMBER);

        if (is_command) {
            // Start new command
            current_cmd.params.clear();

            switch (token.type) {
                case MOVETO_ABS:
                    current_cmd.type = 'M';
                    current_cmd.relative = false;
                    last_cmd_type = 'M';
                    last_cmd_relative = false;
                    break;
                case MOVETO_REL:
                    current_cmd.type = 'M';
                    current_cmd.relative = true;
                    last_cmd_type = 'M';
                    last_cmd_relative = true;
                    break;
                case LINETO_ABS:
                    current_cmd.type = 'L';
                    current_cmd.relative = false;
                    last_cmd_type = 'L';
                    last_cmd_relative = false;
                    break;
                case LINETO_REL:
                    current_cmd.type = 'L';
                    current_cmd.relative = true;
                    last_cmd_type = 'L';
                    last_cmd_relative = true;
                    break;
                case HLINETO_ABS:
                    current_cmd.type = 'H';
                    current_cmd.relative = false;
                    last_cmd_type = 'H';
                    last_cmd_relative = false;
                    break;
                case HLINETO_REL:
                    current_cmd.type = 'H';
                    current_cmd.relative = true;
                    last_cmd_type = 'H';
                    last_cmd_relative = true;
                    break;
                case VLINETO_ABS:
                    current_cmd.type = 'V';
                    current_cmd.relative = false;
                    last_cmd_type = 'V';
                    last_cmd_relative = false;
                    break;
                case VLINETO_REL:
                    current_cmd.type = 'V';
                    current_cmd.relative = true;
                    last_cmd_type = 'V';
                    last_cmd_relative = true;
                    break;
                case CURVETO_ABS:
                    current_cmd.type = 'C';
                    current_cmd.relative = false;
                    last_cmd_type = 'C';
                    last_cmd_relative = false;
                    break;
                case CURVETO_REL:
                    current_cmd.type = 'C';
                    current_cmd.relative = true;
                    last_cmd_type = 'C';
                    last_cmd_relative = true;
                    break;
                case SMOOTHCURVETO_ABS:
                    current_cmd.type = 'S';
                    current_cmd.relative = false;
                    last_cmd_type = 'S';
                    last_cmd_relative = false;
                    break;
                case SMOOTHCURVETO_REL:
                    current_cmd.type = 'S';
                    current_cmd.relative = true;
                    last_cmd_type = 'S';
                    last_cmd_relative = true;
                    break;
                case QUADTO_ABS:
                    current_cmd.type = 'Q';
                    current_cmd.relative = false;
                    last_cmd_type = 'Q';
                    last_cmd_relative = false;
                    break;
                case QUADTO_REL:
                    current_cmd.type = 'Q';
                    current_cmd.relative = true;
                    last_cmd_type = 'Q';
                    last_cmd_relative = true;
                    break;
                case SMOOTHQUADTO_ABS:
                    current_cmd.type = 'T';
                    current_cmd.relative = false;
                    last_cmd_type = 'T';
                    last_cmd_relative = false;
                    break;
                case SMOOTHQUADTO_REL:
                    current_cmd.type = 'T';
                    current_cmd.relative = true;
                    last_cmd_type = 'T';
                    last_cmd_relative = true;
                    break;
                case ARC_ABS:
                    current_cmd.type = 'A';
                    current_cmd.relative = false;
                    last_cmd_type = 'A';
                    last_cmd_relative = false;
                    break;
                case ARC_REL:
                    current_cmd.type = 'A';
                    current_cmd.relative = true;
                    last_cmd_type = 'A';
                    last_cmd_relative = true;
                    break;
                case CLOSEPATH:
                    current_cmd.type = 'Z';
                    current_cmd.relative = false;
                    commands.push_back(current_cmd);
                    continue;  // Z has no parameters
                default:
                    continue;
            }

            // Determine how many parameters this command needs
            int param_count = 0;
            switch (current_cmd.type) {
                case 'M': case 'L': case 'T': param_count = 2; break;
                case 'H': case 'V': param_count = 1; break;
                case 'C': param_count = 6; break;
                case 'S': case 'Q': param_count = 4; break;
                case 'A': param_count = 7; break;
                default: param_count = 0;
            }

            // Read parameters
            for (int i = 0; i < param_count; i++) {
                token = SVGPathLexer_next_token(&lexer);
                if (token.type != NUMBER) {
                    break;  // Malformed path
                }
                current_cmd.params.push_back(token.value);
            }

            commands.push_back(current_cmd);

        } else {
            // NUMBER token without command = implicit command repetition
            // Handle implicit commands (e.g., "M 10 10 20 20" -> "M 10 10 L 20 20")

            if (last_cmd_type == 0) continue;  // No previous command

            PathCommand implicit_cmd;
            implicit_cmd.relative = last_cmd_relative;

            // M becomes L after first point
            if (last_cmd_type == 'M') {
                implicit_cmd.type = 'L';
            } else {
                implicit_cmd.type = last_cmd_type;
            }

            // Determine parameter count
            int param_count = 0;
            switch (implicit_cmd.type) {
                case 'M': case 'L': case 'T': param_count = 2; break;
                case 'H': case 'V': param_count = 1; break;
                case 'C': param_count = 6; break;
                case 'S': case 'Q': param_count = 4; break;
                case 'A': param_count = 7; break;
                default: continue;
            }

            // First number is already in token
            implicit_cmd.params.push_back(token.value);

            // Read remaining parameters
            for (int i = 1; i < param_count; i++) {
                token = SVGPathLexer_next_token(&lexer);
                if (token.type != NUMBER) {
                    break;
                }
                implicit_cmd.params.push_back(token.value);
            }

            commands.push_back(implicit_cmd);
        }
    }

    return commands;
}

} // namespace cssbox
