block-beta
    columns 1
    db["DB"]
    blockArrowId6["&nbsp;&nbsp;&nbsp;"]
    block:ID
        A["A"]
        B["A wide one in the middle"]
        C["C"]
    end
    space
    D["D"]
    style B fill:#969,stroke:#333,stroke-width:4px