#pragma once

#include <string>

// Include lemon-generated token definitions
// This header is generated by lemon in the build directory
#include "infographic_parser_gen.h"

namespace flex::modules::infographic {

// Special Token Types
constexpr int TOK_EOF = 0;
constexpr int TOK_ERROR = -1;

struct Token {
    int type;
    std::string value;
    int line;
    int column;

    Token(int t = TOK_EOF, std::string v = "", int l = 0, int c = 0)
        : type(t), value(v), line(l), column(c) {}
};

struct LexerState {
    const char* start;
    const char* cursor;
    const char* marker;
    int line;
    int column;
};

// Lexer interface
Token lex_next_token(LexerState* state);
LexerState* lexer_create(const char* source);
void lexer_destroy(LexerState* state);

} // namespace flex::modules::infographic
