#pragma once

#include <string>
#include <memory>
#include <vector>

// Include lemon-generated token definitions (TOK_TITLE, TOK_BAR, etc.)
// This header is generated by lemon in the build directory
#include "chart_parser_gen.h"

namespace flex {
namespace chart {

// ============================================================================
// Special Token Types (not in grammar, lemon uses 0 for EOF internally)
// ============================================================================

constexpr int TOK_EOF = 0;
constexpr int TOK_ERROR = -1;

// ============================================================================
// Token Structure
// ============================================================================

struct Token {
    int type;
    std::string value;
    int line;
    int column;

    Token(int t = TOK_EOF, std::string v = "", int l = 0, int c = 0)
        : type(t), value(v), line(l), column(c) {}
};

// ============================================================================
// Lexer State
// ============================================================================

struct LexerState {
    const char *start;
    const char *cursor;
    const char *marker;
    int line;
    int column;
};

// ============================================================================
// Lexer Interface
// ============================================================================

Token lex_next_token(LexerState *state);
LexerState *lexer_create(const char *source);
void lexer_destroy(LexerState *state);

} // namespace chart
} // namespace flex
