/*
 * CSS Keyword Lexer - Fast DFA-based CSS keyword parsing
 *
 * Generated by re2c, this provides O(n) keyword matching
 * with zero allocations (no to_lowercase() needed).
 *
 * Usage:
 *   #include "css_keyword_lexer.h"
 *   using namespace cssbox::fast;
 *   
 *   auto display = parse_display("flex");  // Returns Display::FLEX
 *   auto color = parse_named_color("red"); // Returns {255, 0, 0, 255, valid=true}
 */

#ifndef CSS_KEYWORD_LEXER_H
#define CSS_KEYWORD_LEXER_H

#include <string_view>
#include <cstdint>
#include <ctype.h>

// ============================================================================
// C-style enums for lexer output (must match re2c generated code)
// ============================================================================

extern "C" {

// Display values
typedef enum {
    CSS_DISPLAY_UNKNOWN = 0,
    CSS_DISPLAY_BLOCK,
    CSS_DISPLAY_INLINE,
    CSS_DISPLAY_INLINE_BLOCK,
    CSS_DISPLAY_FLEX,
    CSS_DISPLAY_INLINE_FLEX,
    CSS_DISPLAY_GRID,
    CSS_DISPLAY_INLINE_GRID,
    CSS_DISPLAY_NONE,
    CSS_DISPLAY_CONTENTS
} CSSDisplayValue;

typedef enum {
    CSS_POSITION_UNKNOWN = 0,
    CSS_POSITION_STATIC,
    CSS_POSITION_RELATIVE,
    CSS_POSITION_ABSOLUTE,
    CSS_POSITION_FIXED,
    CSS_POSITION_STICKY
} CSSPositionValue;

typedef enum {
    CSS_OVERFLOW_UNKNOWN = 0,
    CSS_OVERFLOW_VISIBLE,
    CSS_OVERFLOW_HIDDEN,
    CSS_OVERFLOW_SCROLL,
    CSS_OVERFLOW_AUTO
} CSSOverflowValue;

typedef enum {
    CSS_BOX_SIZING_UNKNOWN = 0,
    CSS_BOX_SIZING_CONTENT_BOX,
    CSS_BOX_SIZING_BORDER_BOX
} CSSBoxSizingValue;

typedef enum {
    CSS_FLEX_DIR_UNKNOWN = 0,
    CSS_FLEX_DIR_ROW,
    CSS_FLEX_DIR_ROW_REVERSE,
    CSS_FLEX_DIR_COLUMN,
    CSS_FLEX_DIR_COLUMN_REVERSE
} CSSFlexDirectionValue;

typedef enum {
    CSS_FLEX_WRAP_UNKNOWN = 0,
    CSS_FLEX_WRAP_NOWRAP,
    CSS_FLEX_WRAP_WRAP,
    CSS_FLEX_WRAP_WRAP_REVERSE
} CSSFlexWrapValue;

typedef enum {
    CSS_JUSTIFY_UNKNOWN = 0,
    CSS_JUSTIFY_FLEX_START,
    CSS_JUSTIFY_FLEX_END,
    CSS_JUSTIFY_CENTER,
    CSS_JUSTIFY_SPACE_BETWEEN,
    CSS_JUSTIFY_SPACE_AROUND,
    CSS_JUSTIFY_SPACE_EVENLY,
    CSS_JUSTIFY_START,
    CSS_JUSTIFY_END
} CSSJustifyContentValue;

typedef enum {
    CSS_ALIGN_ITEMS_UNKNOWN = 0,
    CSS_ALIGN_ITEMS_FLEX_START,
    CSS_ALIGN_ITEMS_FLEX_END,
    CSS_ALIGN_ITEMS_CENTER,
    CSS_ALIGN_ITEMS_BASELINE,
    CSS_ALIGN_ITEMS_STRETCH,
    CSS_ALIGN_ITEMS_START,
    CSS_ALIGN_ITEMS_END
} CSSAlignItemsValue;

typedef enum {
    CSS_ALIGN_CONTENT_UNKNOWN = 0,
    CSS_ALIGN_CONTENT_FLEX_START,
    CSS_ALIGN_CONTENT_FLEX_END,
    CSS_ALIGN_CONTENT_CENTER,
    CSS_ALIGN_CONTENT_SPACE_BETWEEN,
    CSS_ALIGN_CONTENT_SPACE_AROUND,
    CSS_ALIGN_CONTENT_STRETCH
} CSSAlignContentValue;

typedef enum {
    CSS_SELF_ALIGN_UNKNOWN = 0,
    CSS_SELF_ALIGN_AUTO,
    CSS_SELF_ALIGN_START,
    CSS_SELF_ALIGN_END,
    CSS_SELF_ALIGN_CENTER,
    CSS_SELF_ALIGN_BASELINE,
    CSS_SELF_ALIGN_STRETCH,
    CSS_SELF_ALIGN_FLEX_START,
    CSS_SELF_ALIGN_FLEX_END
} CSSSelfAlignValue;

typedef enum {
    CSS_BORDER_STYLE_UNKNOWN = 0,
    CSS_BORDER_STYLE_NONE,
    CSS_BORDER_STYLE_SOLID,
    CSS_BORDER_STYLE_DASHED,
    CSS_BORDER_STYLE_DOTTED,
    CSS_BORDER_STYLE_DOUBLE,
    CSS_BORDER_STYLE_HIDDEN,
    CSS_BORDER_STYLE_GROOVE,
    CSS_BORDER_STYLE_RIDGE,
    CSS_BORDER_STYLE_INSET,
    CSS_BORDER_STYLE_OUTSET
} CSSBorderStyleValue;

typedef enum {
    CSS_TEXT_ALIGN_UNKNOWN = 0,
    CSS_TEXT_ALIGN_LEFT,
    CSS_TEXT_ALIGN_CENTER,
    CSS_TEXT_ALIGN_RIGHT,
    CSS_TEXT_ALIGN_JUSTIFY
} CSSTextAlignValue;

typedef enum {
    CSS_VERTICAL_ALIGN_UNKNOWN = 0,
    CSS_VERTICAL_ALIGN_TOP,
    CSS_VERTICAL_ALIGN_MIDDLE,
    CSS_VERTICAL_ALIGN_BOTTOM,
    CSS_VERTICAL_ALIGN_BASELINE
} CSSVerticalAlignValue;

typedef enum {
    CSS_FONT_WEIGHT_UNKNOWN = 0,
    CSS_FONT_WEIGHT_NORMAL,
    CSS_FONT_WEIGHT_BOLD,
    CSS_FONT_WEIGHT_LIGHTER,
    CSS_FONT_WEIGHT_BOLDER,
    CSS_FONT_WEIGHT_100,
    CSS_FONT_WEIGHT_200,
    CSS_FONT_WEIGHT_300,
    CSS_FONT_WEIGHT_400,
    CSS_FONT_WEIGHT_500,
    CSS_FONT_WEIGHT_600,
    CSS_FONT_WEIGHT_700,
    CSS_FONT_WEIGHT_800,
    CSS_FONT_WEIGHT_900
} CSSFontWeightValue;

typedef enum {
    CSS_FONT_STYLE_UNKNOWN = 0,
    CSS_FONT_STYLE_NORMAL,
    CSS_FONT_STYLE_ITALIC,
    CSS_FONT_STYLE_OBLIQUE
} CSSFontStyleValue;

typedef enum {
    CSS_TEXT_DECORATION_UNKNOWN = 0,
    CSS_TEXT_DECORATION_NONE,
    CSS_TEXT_DECORATION_UNDERLINE,
    CSS_TEXT_DECORATION_OVERLINE,
    CSS_TEXT_DECORATION_LINE_THROUGH
} CSSTextDecorationValue;

typedef enum {
    CSS_TEXT_TRANSFORM_UNKNOWN = 0,
    CSS_TEXT_TRANSFORM_NONE,
    CSS_TEXT_TRANSFORM_UPPERCASE,
    CSS_TEXT_TRANSFORM_LOWERCASE,
    CSS_TEXT_TRANSFORM_CAPITALIZE
} CSSTextTransformValue;

typedef enum {
    CSS_LINE_CAP_UNKNOWN = 0,
    CSS_LINE_CAP_BUTT,
    CSS_LINE_CAP_ROUND,
    CSS_LINE_CAP_SQUARE
} CSSLineCapValue;

typedef enum {
    CSS_LINE_JOIN_UNKNOWN = 0,
    CSS_LINE_JOIN_MITER,
    CSS_LINE_JOIN_ROUND,
    CSS_LINE_JOIN_BEVEL
} CSSLineJoinValue;

typedef enum {
    CSS_TRANS_PROP_UNKNOWN = 0,
    CSS_TRANS_PROP_NONE,
    CSS_TRANS_PROP_ALL,
    CSS_TRANS_PROP_WIDTH,
    CSS_TRANS_PROP_HEIGHT,
    CSS_TRANS_PROP_MIN_WIDTH,
    CSS_TRANS_PROP_MIN_HEIGHT,
    CSS_TRANS_PROP_MAX_WIDTH,
    CSS_TRANS_PROP_MAX_HEIGHT,
    CSS_TRANS_PROP_PADDING,
    CSS_TRANS_PROP_PADDING_TOP,
    CSS_TRANS_PROP_PADDING_RIGHT,
    CSS_TRANS_PROP_PADDING_BOTTOM,
    CSS_TRANS_PROP_PADDING_LEFT,
    CSS_TRANS_PROP_MARGIN,
    CSS_TRANS_PROP_MARGIN_TOP,
    CSS_TRANS_PROP_MARGIN_RIGHT,
    CSS_TRANS_PROP_MARGIN_BOTTOM,
    CSS_TRANS_PROP_MARGIN_LEFT,
    CSS_TRANS_PROP_TOP,
    CSS_TRANS_PROP_RIGHT,
    CSS_TRANS_PROP_BOTTOM,
    CSS_TRANS_PROP_LEFT,
    CSS_TRANS_PROP_OPACITY,
    CSS_TRANS_PROP_BACKGROUND_COLOR,
    CSS_TRANS_PROP_COLOR,
    CSS_TRANS_PROP_BORDER_COLOR,
    CSS_TRANS_PROP_BORDER_WIDTH,
    CSS_TRANS_PROP_BORDER_RADIUS,
    CSS_TRANS_PROP_TRANSFORM,
    CSS_TRANS_PROP_FLEX_GROW,
    CSS_TRANS_PROP_FLEX_SHRINK,
    CSS_TRANS_PROP_GAP,
    CSS_TRANS_PROP_FILL,
    CSS_TRANS_PROP_STROKE,
    CSS_TRANS_PROP_STROKE_WIDTH,
    CSS_TRANS_PROP_FILTER
} CSSTransitionPropertyValue;

typedef enum {
    CSS_TIMING_UNKNOWN = 0,
    CSS_TIMING_LINEAR,
    CSS_TIMING_EASE,
    CSS_TIMING_EASE_IN,
    CSS_TIMING_EASE_OUT,
    CSS_TIMING_EASE_IN_OUT
} CSSTimingKeywordValue;

typedef enum {
    CSS_ANIM_DIR_UNKNOWN = 0,
    CSS_ANIM_DIR_NORMAL,
    CSS_ANIM_DIR_REVERSE,
    CSS_ANIM_DIR_ALTERNATE,
    CSS_ANIM_DIR_ALTERNATE_REVERSE
} CSSAnimationDirectionValue;

typedef enum {
    CSS_ANIM_FILL_UNKNOWN = 0,
    CSS_ANIM_FILL_NONE,
    CSS_ANIM_FILL_FORWARDS,
    CSS_ANIM_FILL_BACKWARDS,
    CSS_ANIM_FILL_BOTH
} CSSAnimationFillModeValue;

typedef enum {
    CSS_ANIM_PLAY_UNKNOWN = 0,
    CSS_ANIM_PLAY_RUNNING,
    CSS_ANIM_PLAY_PAUSED
} CSSAnimationPlayStateValue;

typedef enum {
    CSS_TRANSFORM_UNKNOWN = 0,
    CSS_TRANSFORM_TRANSLATE,
    CSS_TRANSFORM_TRANSLATEX,
    CSS_TRANSFORM_TRANSLATEY,
    CSS_TRANSFORM_ROTATE,
    CSS_TRANSFORM_SCALE,
    CSS_TRANSFORM_SCALEX,
    CSS_TRANSFORM_SCALEY,
    CSS_TRANSFORM_SKEW,
    CSS_TRANSFORM_SKEWX,
    CSS_TRANSFORM_SKEWY,
    CSS_TRANSFORM_MATRIX
} CSSTransformFunctionValue;

typedef enum {
    CSS_UNIT_UNKNOWN = 0,
    CSS_UNIT_PX,
    CSS_UNIT_PERCENT,
    CSS_UNIT_EM,
    CSS_UNIT_REM,
    CSS_UNIT_VW,
    CSS_UNIT_VH,
    CSS_UNIT_NONE
} CSSLengthUnitValue;

typedef enum {
    CSS_KF_PROP_UNKNOWN = 0,
    CSS_KF_PROP_OPACITY,
    CSS_KF_PROP_BACKGROUND_COLOR,
    CSS_KF_PROP_BACKGROUND,
    CSS_KF_PROP_COLOR,
    CSS_KF_PROP_TRANSFORM,
    CSS_KF_PROP_WIDTH,
    CSS_KF_PROP_HEIGHT,
    CSS_KF_PROP_BORDER_RADIUS,
    CSS_KF_PROP_BORDER_COLOR,
    CSS_KF_PROP_BORDER_WIDTH
} CSSKeyframePropertyValue;

typedef enum {
    CSS_ELEM_UNKNOWN = 0,
    CSS_ELEM_TEXT,
    CSS_ELEM_SPAN,
    CSS_ELEM_LINE,
    CSS_ELEM_CIRCLE,
    CSS_ELEM_ELLIPSE,
    CSS_ELEM_RECT,
    CSS_ELEM_PATH,
    CSS_ELEM_POLYGON,
    CSS_ELEM_POLYLINE,
    CSS_ELEM_SVG,
    CSS_ELEM_TEXTPATH,
    CSS_ELEM_G,
    CSS_ELEM_DEFS,
    CSS_ELEM_USE,
    CSS_ELEM_IMAGE,
    CSS_ELEM_DIV
} CSSElementTypeValue;

typedef enum {
    CSS_POS_UNKNOWN = 0,
    CSS_POS_LEFT,
    CSS_POS_CENTER,
    CSS_POS_RIGHT,
    CSS_POS_TOP,
    CSS_POS_BOTTOM
} CSSPositionKeywordValue;

typedef enum {
    CSS_PSEUDO_UNKNOWN = 0,
    CSS_PSEUDO_FIRST_CHILD,
    CSS_PSEUDO_LAST_CHILD,
    CSS_PSEUDO_ONLY_CHILD,
    CSS_PSEUDO_NTH_CHILD,
    CSS_PSEUDO_NTH_LAST_CHILD,
    CSS_PSEUDO_FIRST_OF_TYPE,
    CSS_PSEUDO_LAST_OF_TYPE,
    CSS_PSEUDO_ONLY_OF_TYPE
} CSSStructuralPseudoValue;

typedef enum {
    CSS_NTH_UNKNOWN = 0,
    CSS_NTH_ODD,
    CSS_NTH_EVEN
} CSSNthKeywordValue;

typedef struct {
    uint8_t r, g, b, a;
    int valid;
} CSSNamedColor;

// C function declarations (implemented in generated css_keyword_lexer_gen.c)
int css_parse_display(const char* str, size_t len);
int css_parse_position(const char* str, size_t len);
int css_parse_overflow(const char* str, size_t len);
int css_parse_box_sizing(const char* str, size_t len);
int css_parse_flex_direction(const char* str, size_t len);
int css_parse_flex_wrap(const char* str, size_t len);
int css_parse_justify_content(const char* str, size_t len);
int css_parse_align_items(const char* str, size_t len);
int css_parse_align_content(const char* str, size_t len);
int css_parse_self_align(const char* str, size_t len);
int css_parse_border_style(const char* str, size_t len);
int css_parse_text_align(const char* str, size_t len);
int css_parse_vertical_align(const char* str, size_t len);
int css_parse_font_weight(const char* str, size_t len);
int css_parse_font_style(const char* str, size_t len);
int css_parse_text_decoration(const char* str, size_t len);
int css_parse_text_transform(const char* str, size_t len);
int css_parse_line_cap(const char* str, size_t len);
int css_parse_line_join(const char* str, size_t len);
CSSNamedColor css_parse_named_color(const char* str, size_t len);
int css_parse_transition_property(const char* str, size_t len);
int css_parse_timing_keyword(const char* str, size_t len);
int css_parse_animation_direction(const char* str, size_t len);
int css_parse_animation_fill_mode(const char* str, size_t len);
int css_parse_animation_play_state(const char* str, size_t len);
int css_parse_transform_function(const char* str, size_t len);
int css_parse_length_unit(const char* str, size_t len);
int css_parse_keyframe_property(const char* str, size_t len);
int css_parse_element_type(const char* str, size_t len);
int css_parse_position_keyword(const char* str, size_t len);
int css_parse_structural_pseudo(const char* str, size_t len);
int css_parse_nth_keyword(const char* str, size_t len);

} // extern "C"

// ============================================================================
// C++ inline wrappers with string_view support
// ============================================================================

namespace cssbox {
namespace fast {

inline void trim_bounds(const char** start, const char** end) {
    while (*start < *end && isspace((unsigned char)**start)) (*start)++;
    while (*end > *start && isspace((unsigned char)(*(*end - 1)))) (*end)--;
}

inline int parse_display(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_display(start, end - start);
}

inline int parse_position(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_position(start, end - start);
}

inline int parse_overflow(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_overflow(start, end - start);
}

inline int parse_box_sizing(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_box_sizing(start, end - start);
}

inline int parse_flex_direction(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_flex_direction(start, end - start);
}

inline int parse_flex_wrap(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_flex_wrap(start, end - start);
}

inline int parse_justify_content(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_justify_content(start, end - start);
}

inline int parse_align_items(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_align_items(start, end - start);
}

inline int parse_align_content(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_align_content(start, end - start);
}

inline int parse_self_align(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_self_align(start, end - start);
}

inline int parse_border_style(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_border_style(start, end - start);
}

inline int parse_text_align(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_text_align(start, end - start);
}

inline int parse_vertical_align(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_vertical_align(start, end - start);
}

inline int parse_font_weight(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_font_weight(start, end - start);
}

inline int parse_font_style(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_font_style(start, end - start);
}

inline int parse_text_decoration(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_text_decoration(start, end - start);
}

inline int parse_text_transform(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_text_transform(start, end - start);
}

inline int parse_line_cap(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_line_cap(start, end - start);
}

inline int parse_line_join(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_line_join(start, end - start);
}

inline CSSNamedColor parse_named_color(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_named_color(start, end - start);
}

inline int parse_transition_property(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_transition_property(start, end - start);
}

inline int parse_timing_keyword(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_timing_keyword(start, end - start);
}

inline int parse_animation_direction(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_animation_direction(start, end - start);
}

inline int parse_animation_fill_mode(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_animation_fill_mode(start, end - start);
}

inline int parse_animation_play_state(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_animation_play_state(start, end - start);
}

inline int parse_transform_function(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_transform_function(start, end - start);
}

inline int parse_length_unit(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_length_unit(start, end - start);
}

inline int parse_keyframe_property(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_keyframe_property(start, end - start);
}

inline int parse_element_type(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_element_type(start, end - start);
}

inline int parse_position_keyword(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_position_keyword(start, end - start);
}

inline int parse_structural_pseudo(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_structural_pseudo(start, end - start);
}

inline int parse_nth_keyword(std::string_view str) {
    const char* start = str.data();
    const char* end = start + str.size();
    trim_bounds(&start, &end);
    return css_parse_nth_keyword(start, end - start);
}

} // namespace fast
} // namespace cssbox

#endif // CSS_KEYWORD_LEXER_H
