classDiagram
    Class01 <|-- AveryLongClass : Inheritance
    Class03 *-- Class04 : Composition
    Class05 o-- Class06 : Aggregation
    Class07 .. Class08 : Link
    Class09 --> Class10 : Association