flowchart LR
    A[red<br>text] -->|red<br>text| B(blue<br>text)
    C[/red<br/>text/] -->|blue<br/>text| D{blue<br/>text}
    E{{default<br />style}} -->|default<br />style| F([default<br />style])
    click B href "index.html#link-clicked"
    click D testClick
    linkStyle default color:Sienna
    linkStyle 0 color:red
    linkStyle 1 stroke:DarkGray,stroke-width:2px,color:#0000ff