flowchart LR
    47(SAM.CommonFA.FMESummary) --> 48(SAM.CommonFA.CommonFAFinanceBudget)
    37(SAM.CommonFA.BudgetSubserviceLineVolume) --> 48
    35(SAM.CommonFA.PopulationFME) --> 47
    35 --> 45(SAM.CommonFA.MetricPreOpportunity)
    35 --> 39(SAM.CommonFA.ChargeDetails)
    41(SAM.CommonFA.MetricCost) --> 47
    41 --> 45
    41 --> 44(SAM.CommonFA.MetricOutliers)
    46(SAM.CommonFA.MetricOpportunity) --> 47
    40(SAM.CommonFA.OPVisits) --> 47
    38(SAM.CommonFA.CommonFAFinanceRefund) --> 47
    43(SAM.CommonFA.CommonFAFinancePicuDays) --> 47
    42(SAM.CommonFA.CommonFAFinanceNurseryDays) --> 47
    36(SAM.CommonFA.PremetricCost) --> 39
    44 --> 47
    45 --> 46
    39 --> 43
    39 --> 42
    39 --> 41
    39 --> 40