flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    C{Let me thinksssss<br/>ssssssssssssssssssssss<br/>sssssssssssssssssssssssssss} -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[Car]
    B --> C