flowchart LR
    A[red text] -->|default style| B(blue text)
    C([red text]) -->|default style| D[[blue text]]
    E[(red text)] -->|default style| F((blue text))
    G>red text] -->|default style| H{blue text}
    I{{red text}} -->|default style| J[/blue text/]
    linkStyle default color:Sienna