flowchart TB
    subgraph one
        a2
        a1
        a1 --> a2
    end
    subgraph two
        b2
        b1
        b1 --> b2
    end
    subgraph three
        c2
        c1
        c1 --> c2
    end
    one --> two
    three --> two
    c1 --> a2
    two --> c2