C4Context
title System Context diagram for Internet Banking System
    Person("customerA", "Banking Customer A", "A customer of the bank")
    Person("customerB", "Banking Customer B")
    System("SystemAA", "Internet Banking System", "Allows customers to view account info")
    System_Ext("SystemC", "E-mail system", "The internal e-mail system")
    Rel("customerA", "SystemAA", "Uses")
    Rel("SystemAA", "SystemC", "Sends e-mails", "SMTP")
    Rel("customerB", "SystemAA", "Uses")